"""message

Revision ID: 00f73c37a525
Revises: f5fd2d16b8ed
Create Date: 2023-03-03 15:28:01.632544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f73c37a525'
down_revision = 'f5fd2d16b8ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
