"""message

Revision ID: 203ed6807f02
Revises: a9e20b658861
Create Date: 2023-03-03 19:12:28.256017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203ed6807f02'
down_revision = 'a9e20b658861'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_active')
    # ### end Alembic commands ###
