"""message

Revision ID: 233d116961c0
Revises: 9b43d5c4a2df
Create Date: 2023-03-03 15:32:31.286008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233d116961c0'
down_revision = '9b43d5c4a2df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
