"""message

Revision ID: 5438aca558ab
Revises: 4c858fa679d2
Create Date: 2023-03-01 18:25:10.250064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5438aca558ab'
down_revision = '4c858fa679d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_archived')
    # ### end Alembic commands ###
