"""message

Revision ID: 5dd092cc4b5d
Revises: 233d116961c0
Create Date: 2023-03-03 15:34:46.779490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd092cc4b5d'
down_revision = '233d116961c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
