"""Switch to PostgreSQL

Revision ID: 90d632748e61
Revises: 
Create Date: 2023-03-03 12:23:11.311773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d632748e61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
