"""message

Revision ID: 9b43d5c4a2df
Revises: 00f73c37a525
Create Date: 2023-03-03 15:30:35.348632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b43d5c4a2df'
down_revision = '00f73c37a525'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
