"""message

Revision ID: a9e20b658861
Revises: 90d632748e61
Create Date: 2023-03-03 18:18:06.677271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e20b658861'
down_revision = '90d632748e61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('is_registered', sa.Boolean(), nullable=True))
    op.drop_column('customers', 'ordered')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('ordered', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'is_registered')
    op.drop_column('customers', 'address')
    # ### end Alembic commands ###
