"""message

Revision ID: f5fd2d16b8ed
Revises: 203ed6807f02
Create Date: 2023-03-03 19:15:57.509089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5fd2d16b8ed'
down_revision = '203ed6807f02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
