
EXPRESS_VISA = "Express Visa"
MONTHLY_VISA = "Oylik Visa"
EXPRESS_VISA_CALLBACK = "express_visa"
MONTHLY_VISA_CALLBACK = "monthly_visa"

FIRST_NAME, LAST_NAME, PASSPORT_NUM, PASSPORT_VALID_DATE, NATIONALITY, ADDRESS, BIRTH_DATE, EMAIL, PHONE = range(9)